### ISSUE TITLE
运行abu-master/abupy_ui/历史回测界面操作.ipynb 问题

### ISSUE THREAD

**Issue by helloconch** [bbfamily/abu#10]
abu你好
在运行示例时，在Windows平台下，Chrome报：
`提示
海龟21天趋势突破买入策略已添加成功！
(1410, 'RegisterClass', '类已存在。')
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\py\Quantitative\abu-master\abupy\UtilBu\ABuDTUtil.py", line 164, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\py\Quantitative\abu-master\abupy\UtilBu\ABuOsUtil.py", line 33, in show_msg
    do_show_msg(title, msg)
  File "C:\Users\Administrator\Desktop\py\Quantitative\abu-master\abupy\UtilBu\ABuWinUtil.py", line 39, in show_msg
    MainWindow(to_native_str(title), to_native_str(msg))
  File "C:\Users\Administrator\Desktop\py\Quantitative\abu-master\abupy\UtilBu\ABuWinUtil.py", line 181, in __init__
    class_atom = RegisterClass(wc)
pywintypes.error: (1410, 'RegisterClass', '类已存在。')`

而在Mac下，Chrome浏览器正常

**Comment by bbfamily** [comment]
您好，上面在windows平台上报的信息是警告，并非中断性错误，因为需要适配多种不同的系统以及系统之间的不同版本，必然会有一些系统平台兼容错误，所以一些平台函数的错误会进行捕获不会引起中断操作，这些捕获的错误不会影响任何正常的操作以及结果，比如这个系统pop弹窗，如果很在意警告信息的出现，可以在上层设置logging的显示级别为error级别，就不会再显示这些警告信息，祝好！
