### ISSUE TITLE
A股全市场回测会出现error

### ISSUE THREAD

**Issue by starfire-lzd** [bbfamily/abu#11]
在全市场回测中会报错
错误日志如下
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\develop\tools\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\develop\tools\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\develop\tools\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\develop\tools\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\develop\tools\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\develop\tools\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\develop\tools\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\develop\workspace\python\TestCUDA\AbuFactorBuyBreak.py", line 63, in <module>
    run_loop_back()
  File "D:\develop\workspace\python\TestCUDA\AbuFactorBuyBreak.py", line 53, in run_loop_back
    start='2012-08-08', end='2017-08-08')
  File "D:\develop\tools\Anaconda3\lib\site-packages\abupy\CoreBu\ABu.py", line 109, in run_loop_back
    n_process_pick_stock=n_process_pick)
  File "D:\develop\tools\Anaconda3\lib\site-packages\abupy\AlphaBu\ABuPickStockMaster.py", line 97, in do_pick_stock_with_process
    choice_symbols = ABuMarket.market_train_test_split(ABuEnv.g_split_tt_n_folds, choice_symbols)
  File "D:\develop\tools\Anaconda3\lib\site-packages\abupy\MarketBu\ABuMarket.py", line 288, in market_train_test_split
    os.rename(last_path_train, store_train_name)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\lizhengda\\abu\\data\\cache\\market_train_symbols_hs' -> 'C:\\Users\\lizhengda\\abu\\data\\cache\\market_train_symbols_hs_2018_02_03_09_14_12_509525'
```

**Comment by bbfamily** [comment]
您好，从日志看是在读取切割训练测试数据时另一个进程之前使用过的没有正常关闭，导致PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问，建议运行前保证运行环境中就有一个进程，另外也可以直接删除C:\\Users\\lizhengda\\abu\\data\\cache\\market_train_symbols_hs
